# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI/interfaceGrafos.ui'
#
# Created: Tue Jun 21 11:24:30 2011
#      by: PyQt4 UI code generator 4.8.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_InterfaceQt(object):
    def setupUi(self, InterfaceQt):
        InterfaceQt.setObjectName(_fromUtf8("InterfaceQt"))
        InterfaceQt.resize(742, 485)
        self.centralwidget = QtGui.QWidget(InterfaceQt)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setTabPosition(QtGui.QTabWidget.North)
        self.tabWidget.setTabShape(QtGui.QTabWidget.Rounded)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab_adjacencia = QtGui.QWidget()
        self.tab_adjacencia.setObjectName(_fromUtf8("tab_adjacencia"))
        self.gridLayout_2 = QtGui.QGridLayout(self.tab_adjacencia)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.nome_label = QtGui.QLabel(self.tab_adjacencia)
        self.nome_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.nome_label.setObjectName(_fromUtf8("nome_label"))
        self.horizontalLayout.addWidget(self.nome_label)
        self.nome_edit = QtGui.QLineEdit(self.tab_adjacencia)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.nome_edit.sizePolicy().hasHeightForWidth())
        self.nome_edit.setSizePolicy(sizePolicy)
        self.nome_edit.setObjectName(_fromUtf8("nome_edit"))
        self.horizontalLayout.addWidget(self.nome_edit)
        self.horizontalLayout_8.addLayout(self.horizontalLayout)
        self.verticalLayout_4.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.vertices_label = QtGui.QLabel(self.tab_adjacencia)
        self.vertices_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.vertices_label.setObjectName(_fromUtf8("vertices_label"))
        self.horizontalLayout_2.addWidget(self.vertices_label)
        self.vertices_edit = QtGui.QLineEdit(self.tab_adjacencia)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.vertices_edit.sizePolicy().hasHeightForWidth())
        self.vertices_edit.setSizePolicy(sizePolicy)
        self.vertices_edit.setObjectName(_fromUtf8("vertices_edit"))
        self.horizontalLayout_2.addWidget(self.vertices_edit)
        self.adicionar_vertice_button = QtGui.QPushButton(self.tab_adjacencia)
        self.adicionar_vertice_button.setObjectName(_fromUtf8("adicionar_vertice_button"))
        self.horizontalLayout_2.addWidget(self.adicionar_vertice_button)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.remover_vertice_combo = QtGui.QComboBox(self.tab_adjacencia)
        self.remover_vertice_combo.setObjectName(_fromUtf8("remover_vertice_combo"))
        self.horizontalLayout_3.addWidget(self.remover_vertice_combo)
        self.remover_vertice_button = QtGui.QPushButton(self.tab_adjacencia)
        self.remover_vertice_button.setObjectName(_fromUtf8("remover_vertice_button"))
        self.horizontalLayout_3.addWidget(self.remover_vertice_button)
        self.horizontalLayout_2.addLayout(self.horizontalLayout_3)
        self.verticalLayout_4.addLayout(self.horizontalLayout_2)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.valorar_aresta = QtGui.QCheckBox(self.tab_adjacencia)
        self.valorar_aresta.setTristate(False)
        self.valorar_aresta.setObjectName(_fromUtf8("valorar_aresta"))
        self.horizontalLayout_4.addWidget(self.valorar_aresta)
        self.eh_funcao = QtGui.QCheckBox(self.tab_adjacencia)
        self.eh_funcao.setTristate(False)
        self.eh_funcao.setObjectName(_fromUtf8("eh_funcao"))
        self.horizontalLayout_4.addWidget(self.eh_funcao)
        self.funcao_edit = QtGui.QLineEdit(self.tab_adjacencia)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.funcao_edit.sizePolicy().hasHeightForWidth())
        self.funcao_edit.setSizePolicy(sizePolicy)
        self.funcao_edit.setObjectName(_fromUtf8("funcao_edit"))
        self.horizontalLayout_4.addWidget(self.funcao_edit)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.verticalLayout_4.addLayout(self.verticalLayout)
        self.gridLayout_2.addLayout(self.verticalLayout_4, 0, 0, 1, 1)
        self.tabela_adjacencia = QtGui.QTableWidget(self.tab_adjacencia)
        self.tabela_adjacencia.setObjectName(_fromUtf8("tabela_adjacencia"))
        self.tabela_adjacencia.setColumnCount(0)
        self.tabela_adjacencia.setRowCount(0)
        self.gridLayout_2.addWidget(self.tabela_adjacencia, 1, 0, 1, 1)
        self.gerar_arestas_button = QtGui.QPushButton(self.tab_adjacencia)
        self.gerar_arestas_button.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gerar_arestas_button.sizePolicy().hasHeightForWidth())
        self.gerar_arestas_button.setSizePolicy(sizePolicy)
        self.gerar_arestas_button.setObjectName(_fromUtf8("gerar_arestas_button"))
        self.gridLayout_2.addWidget(self.gerar_arestas_button, 2, 0, 1, 1)
        self.tabWidget.addTab(self.tab_adjacencia, _fromUtf8(""))
        self.pesquisas_prop = QtGui.QWidget()
        self.pesquisas_prop.setObjectName(_fromUtf8("pesquisas_prop"))
        self.gridLayout_6 = QtGui.QGridLayout(self.pesquisas_prop)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.propriedades_frame = QtGui.QFrame(self.pesquisas_prop)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.propriedades_frame.sizePolicy().hasHeightForWidth())
        self.propriedades_frame.setSizePolicy(sizePolicy)
        self.propriedades_frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.propriedades_frame.setFrameShadow(QtGui.QFrame.Raised)
        self.propriedades_frame.setObjectName(_fromUtf8("propriedades_frame"))
        self.gridLayout_5 = QtGui.QGridLayout(self.propriedades_frame)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.eh_regular = QtGui.QCheckBox(self.propriedades_frame)
        self.eh_regular.setEnabled(False)
        self.eh_regular.setCheckable(True)
        self.eh_regular.setChecked(False)
        self.eh_regular.setObjectName(_fromUtf8("eh_regular"))
        self.verticalLayout_3.addWidget(self.eh_regular)
        self.eh_conexo = QtGui.QCheckBox(self.propriedades_frame)
        self.eh_conexo.setEnabled(False)
        self.eh_conexo.setCheckable(True)
        self.eh_conexo.setChecked(False)
        self.eh_conexo.setObjectName(_fromUtf8("eh_conexo"))
        self.verticalLayout_3.addWidget(self.eh_conexo)
        self.eh_arvore = QtGui.QCheckBox(self.propriedades_frame)
        self.eh_arvore.setEnabled(False)
        self.eh_arvore.setCheckable(True)
        self.eh_arvore.setChecked(False)
        self.eh_arvore.setObjectName(_fromUtf8("eh_arvore"))
        self.verticalLayout_3.addWidget(self.eh_arvore)
        self.eh_completo = QtGui.QCheckBox(self.propriedades_frame)
        self.eh_completo.setEnabled(False)
        self.eh_completo.setCheckable(True)
        self.eh_completo.setChecked(False)
        self.eh_completo.setObjectName(_fromUtf8("eh_completo"))
        self.verticalLayout_3.addWidget(self.eh_completo)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.ordem_label = QtGui.QLabel(self.propriedades_frame)
        self.ordem_label.setObjectName(_fromUtf8("ordem_label"))
        self.horizontalLayout_5.addWidget(self.ordem_label)
        self.ordem_resultado = QtGui.QLineEdit(self.propriedades_frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ordem_resultado.sizePolicy().hasHeightForWidth())
        self.ordem_resultado.setSizePolicy(sizePolicy)
        self.ordem_resultado.setReadOnly(True)
        self.ordem_resultado.setObjectName(_fromUtf8("ordem_resultado"))
        self.horizontalLayout_5.addWidget(self.ordem_resultado)
        self.verticalLayout_3.addLayout(self.horizontalLayout_5)
        self.gridLayout_5.addLayout(self.verticalLayout_3, 1, 0, 1, 1)
        self.propriedades_label = QtGui.QLabel(self.propriedades_frame)
        self.propriedades_label.setObjectName(_fromUtf8("propriedades_label"))
        self.gridLayout_5.addWidget(self.propriedades_label, 0, 0, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(20, 10, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.MinimumExpanding)
        self.gridLayout_5.addItem(spacerItem1, 2, 0, 1, 1)
        self.gridLayout_6.addWidget(self.propriedades_frame, 0, 1, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_6.addItem(spacerItem2, 1, 1, 1, 1)
        self.pesquisas_frame = QtGui.QFrame(self.pesquisas_prop)
        self.pesquisas_frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.pesquisas_frame.setFrameShadow(QtGui.QFrame.Raised)
        self.pesquisas_frame.setObjectName(_fromUtf8("pesquisas_frame"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.pesquisas_frame)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.label_4 = QtGui.QLabel(self.pesquisas_frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.verticalLayout_2.addWidget(self.label_4)
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.fecho_label = QtGui.QLabel(self.pesquisas_frame)
        self.fecho_label.setObjectName(_fromUtf8("fecho_label"))
        self.gridLayout_3.addWidget(self.fecho_label, 0, 0, 1, 1)
        self.fecho_origem = QtGui.QComboBox(self.pesquisas_frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fecho_origem.sizePolicy().hasHeightForWidth())
        self.fecho_origem.setSizePolicy(sizePolicy)
        self.fecho_origem.setMaximumSize(QtCore.QSize(150, 16777215))
        self.fecho_origem.setObjectName(_fromUtf8("fecho_origem"))
        self.gridLayout_3.addWidget(self.fecho_origem, 0, 1, 1, 1)
        self.fecho_resultado = QtGui.QLineEdit(self.pesquisas_frame)
        self.fecho_resultado.setDragEnabled(False)
        self.fecho_resultado.setReadOnly(True)
        self.fecho_resultado.setObjectName(_fromUtf8("fecho_resultado"))
        self.gridLayout_3.addWidget(self.fecho_resultado, 0, 2, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_3)
        self.line = QtGui.QFrame(self.pesquisas_frame)
        self.line.setLineWidth(1)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.verticalLayout_2.addWidget(self.line)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.informacoes_label = QtGui.QLabel(self.pesquisas_frame)
        self.informacoes_label.setObjectName(_fromUtf8("informacoes_label"))
        self.horizontalLayout_6.addWidget(self.informacoes_label)
        self.informacoes_vertice = QtGui.QComboBox(self.pesquisas_frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.informacoes_vertice.sizePolicy().hasHeightForWidth())
        self.informacoes_vertice.setSizePolicy(sizePolicy)
        self.informacoes_vertice.setMaximumSize(QtCore.QSize(150, 16777215))
        self.informacoes_vertice.setObjectName(_fromUtf8("informacoes_vertice"))
        self.horizontalLayout_6.addWidget(self.informacoes_vertice)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem3)
        self.informacoes_button = QtGui.QPushButton(self.pesquisas_frame)
        self.informacoes_button.setObjectName(_fromUtf8("informacoes_button"))
        self.horizontalLayout_6.addWidget(self.informacoes_button)
        self.verticalLayout_2.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.busca_label_de = QtGui.QLabel(self.pesquisas_frame)
        self.busca_label_de.setObjectName(_fromUtf8("busca_label_de"))
        self.horizontalLayout_7.addWidget(self.busca_label_de)
        self.busca_origem = QtGui.QComboBox(self.pesquisas_frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.busca_origem.sizePolicy().hasHeightForWidth())
        self.busca_origem.setSizePolicy(sizePolicy)
        self.busca_origem.setMaximumSize(QtCore.QSize(150, 16777215))
        self.busca_origem.setObjectName(_fromUtf8("busca_origem"))
        self.horizontalLayout_7.addWidget(self.busca_origem)
        self.busca_label_para = QtGui.QLabel(self.pesquisas_frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.busca_label_para.sizePolicy().hasHeightForWidth())
        self.busca_label_para.setSizePolicy(sizePolicy)
        self.busca_label_para.setObjectName(_fromUtf8("busca_label_para"))
        self.horizontalLayout_7.addWidget(self.busca_label_para)
        self.busca_destino = QtGui.QComboBox(self.pesquisas_frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.busca_destino.sizePolicy().hasHeightForWidth())
        self.busca_destino.setSizePolicy(sizePolicy)
        self.busca_destino.setMaximumSize(QtCore.QSize(150, 16777215))
        self.busca_destino.setObjectName(_fromUtf8("busca_destino"))
        self.horizontalLayout_7.addWidget(self.busca_destino)
        self.busca_profundidade_button = QtGui.QPushButton(self.pesquisas_frame)
        self.busca_profundidade_button.setObjectName(_fromUtf8("busca_profundidade_button"))
        self.horizontalLayout_7.addWidget(self.busca_profundidade_button)
        self.verticalLayout_2.addLayout(self.horizontalLayout_7)
        self.busca_resultado = QtGui.QListWidget(self.pesquisas_frame)
        self.busca_resultado.setTabKeyNavigation(True)
        self.busca_resultado.setAlternatingRowColors(True)
        self.busca_resultado.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.busca_resultado.setViewMode(QtGui.QListView.ListMode)
        self.busca_resultado.setObjectName(_fromUtf8("busca_resultado"))
        self.verticalLayout_2.addWidget(self.busca_resultado)
        self.gridLayout_6.addWidget(self.pesquisas_frame, 0, 0, 1, 1)
        self.tabWidget.addTab(self.pesquisas_prop, _fromUtf8(""))
        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 1)
        InterfaceQt.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(InterfaceQt)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 742, 24))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuMenu = QtGui.QMenu(self.menubar)
        self.menuMenu.setObjectName(_fromUtf8("menuMenu"))
        InterfaceQt.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(InterfaceQt)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        InterfaceQt.setStatusBar(self.statusbar)
        self.actionSair = QtGui.QAction(InterfaceQt)
        self.actionSair.setObjectName(_fromUtf8("actionSair"))
        self.menuMenu.addAction(self.actionSair)
        self.menubar.addAction(self.menuMenu.menuAction())
        self.nome_label.setBuddy(self.nome_edit)
        self.vertices_label.setBuddy(self.vertices_edit)
        self.fecho_label.setBuddy(self.fecho_origem)
        self.informacoes_label.setBuddy(self.informacoes_vertice)
        self.busca_label_de.setBuddy(self.busca_origem)

        self.retranslateUi(InterfaceQt)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.actionSair, QtCore.SIGNAL(_fromUtf8("triggered()")), InterfaceQt.close)
        QtCore.QMetaObject.connectSlotsByName(InterfaceQt)
        InterfaceQt.setTabOrder(self.tabela_adjacencia, self.fecho_origem)
        InterfaceQt.setTabOrder(self.fecho_origem, self.fecho_resultado)
        InterfaceQt.setTabOrder(self.fecho_resultado, self.informacoes_vertice)
        InterfaceQt.setTabOrder(self.informacoes_vertice, self.informacoes_button)
        InterfaceQt.setTabOrder(self.informacoes_button, self.busca_origem)
        InterfaceQt.setTabOrder(self.busca_origem, self.busca_destino)
        InterfaceQt.setTabOrder(self.busca_destino, self.busca_profundidade_button)
        InterfaceQt.setTabOrder(self.busca_profundidade_button, self.busca_resultado)
        InterfaceQt.setTabOrder(self.busca_resultado, self.eh_regular)
        InterfaceQt.setTabOrder(self.eh_regular, self.eh_conexo)
        InterfaceQt.setTabOrder(self.eh_conexo, self.eh_arvore)
        InterfaceQt.setTabOrder(self.eh_arvore, self.eh_completo)
        InterfaceQt.setTabOrder(self.eh_completo, self.ordem_resultado)

    def retranslateUi(self, InterfaceQt):
        InterfaceQt.setWindowTitle(QtGui.QApplication.translate("InterfaceQt", "Framework de Grafos", None, QtGui.QApplication.UnicodeUTF8))
        self.nome_label.setText(QtGui.QApplication.translate("InterfaceQt", "&Nome:", None, QtGui.QApplication.UnicodeUTF8))
        self.vertices_label.setText(QtGui.QApplication.translate("InterfaceQt", "&Vértice(s)", None, QtGui.QApplication.UnicodeUTF8))
        self.adicionar_vertice_button.setText(QtGui.QApplication.translate("InterfaceQt", "&Adicionar Vértice(s)", None, QtGui.QApplication.UnicodeUTF8))
        self.remover_vertice_button.setText(QtGui.QApplication.translate("InterfaceQt", "Re&mover Vértice", None, QtGui.QApplication.UnicodeUTF8))
        self.valorar_aresta.setText(QtGui.QApplication.translate("InterfaceQt", "Valorar A&restas", None, QtGui.QApplication.UnicodeUTF8))
        self.eh_funcao.setText(QtGui.QApplication.translate("InterfaceQt", "É &Função:", None, QtGui.QApplication.UnicodeUTF8))
        self.gerar_arestas_button.setText(QtGui.QApplication.translate("InterfaceQt", "&Gerar Arestas", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_adjacencia), QtGui.QApplication.translate("InterfaceQt", "Tabela de Adjacência", None, QtGui.QApplication.UnicodeUTF8))
        self.eh_regular.setText(QtGui.QApplication.translate("InterfaceQt", "Regular", None, QtGui.QApplication.UnicodeUTF8))
        self.eh_conexo.setText(QtGui.QApplication.translate("InterfaceQt", "Conexo", None, QtGui.QApplication.UnicodeUTF8))
        self.eh_arvore.setText(QtGui.QApplication.translate("InterfaceQt", "Árvore", None, QtGui.QApplication.UnicodeUTF8))
        self.eh_completo.setText(QtGui.QApplication.translate("InterfaceQt", "Completo", None, QtGui.QApplication.UnicodeUTF8))
        self.ordem_label.setText(QtGui.QApplication.translate("InterfaceQt", "Ordem:", None, QtGui.QApplication.UnicodeUTF8))
        self.propriedades_label.setText(QtGui.QApplication.translate("InterfaceQt", "Propriedades:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("InterfaceQt", "Pesquisas:", None, QtGui.QApplication.UnicodeUTF8))
        self.fecho_label.setText(QtGui.QApplication.translate("InterfaceQt", "&Fecho Transitivo de:", None, QtGui.QApplication.UnicodeUTF8))
        self.informacoes_label.setText(QtGui.QApplication.translate("InterfaceQt", "&Informações de:", None, QtGui.QApplication.UnicodeUTF8))
        self.informacoes_button.setText(QtGui.QApplication.translate("InterfaceQt", "Buscar", None, QtGui.QApplication.UnicodeUTF8))
        self.busca_label_de.setText(QtGui.QApplication.translate("InterfaceQt", "Busca em Profundidade de:", None, QtGui.QApplication.UnicodeUTF8))
        self.busca_label_para.setText(QtGui.QApplication.translate("InterfaceQt", "para:", None, QtGui.QApplication.UnicodeUTF8))
        self.busca_profundidade_button.setText(QtGui.QApplication.translate("InterfaceQt", "&Buscar", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.pesquisas_prop), QtGui.QApplication.translate("InterfaceQt", "Pesquisas/Propriedades", None, QtGui.QApplication.UnicodeUTF8))
        self.menuMenu.setTitle(QtGui.QApplication.translate("InterfaceQt", "Menu", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSair.setText(QtGui.QApplication.translate("InterfaceQt", "Sair", None, QtGui.QApplication.UnicodeUTF8))

